### ISSUE TITLE
Doesn't work with tailwind.config.cjs

### ISSUE THREAD

**Issue by andriibieriezhnoi** [ThemePlate/vite-plugin-tailwindcss#1]
Hey.

This plugin doesn't work when your tw config file named as `tailwind.config.cjs`
I can't use default `tailwind.config.js` name because my package.json has a type "module"

Would be nice if you will check both of file formats or add additional argument for plugin call function where I can override path to config

Thanks

**Comment by kermage** [comment]
Please check [v0.3.0](https://github.com/ThemePlate/vite-plugin-tailwindcss/releases/tag/v0.3.0), it should support now all the possible flavors.

**Comment by andriibieriezhnoi** [comment]
> Please check [v0.3.0](https://github.com/ThemePlate/vite-plugin-tailwindcss/releases/tag/v0.3.0), it should support now all the possible flavors.

All good. Thanks <3

**Comment by kermage** [comment]
I'm curious to learn more about the use case you had that led you to raise this issue. Would you mind sharing more details about the specific scenario you were working on? This can help me better understand how my package is being used and potentially uncover other areas for improvement.

Thank you for your valuable contribution to the project!
